-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE block
(
  id SERIAL PRIMARY KEY,
  height integer NOT NULL UNIQUE,
  hash character varying(64) NOT NULL UNIQUE,
  num_txs integer DEFAULT 0,
  total_gas integer DEFAULT 0,
  proposer_address character varying(40) NOT NULL REFERENCES validator(address),
  pre_commits integer NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX block_pkey ON block(id
int4_ops);
CREATE UNIQUE INDEX block_height_key ON block(height
int4_ops);
CREATE UNIQUE INDEX block_hash_key ON block(hash
text_ops);
