-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE block
(
    height           integer                     PRIMARY KEY,
    hash             character varying(64)       NOT NULL UNIQUE,
    num_txs          integer DEFAULT 0,
    total_gas        integer DEFAULT 0,
    proposer_address character varying(52)       NOT NULL REFERENCES validator (consensus_address),
    pre_commits      integer                     NOT NULL,
    timestamp        timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX block_pkey ON block (id int4_ops);
CREATE UNIQUE INDEX block_height_key ON block (height int4_ops);
CREATE UNIQUE INDEX block_hash_key ON block (hash TEXT_PATTERN_OPS);
