-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE pre_commit
(
  id SERIAL PRIMARY KEY,
  height integer NOT NULL,
  round integer NOT NULL,
  validator_address character varying(40) NOT NULL REFERENCES validator(address),
  timestamp timestamp
  without time zone NOT NULL,
    voting_power integer NOT NULL,
    proposer_priority integer NOT NULL
);

  -- Indices -------------------------------------------------------

  CREATE UNIQUE INDEX pre_commit_pkey ON pre_commit(id
  int4_ops);
  CREATE INDEX validator_address_idx ON pre_commit(validator_address
  text_ops);
  CREATE INDEX height_idx ON pre_commit(height
  int4_ops);
  CREATE INDEX round_idx ON pre_commit(round
  int4_ops);
  CREATE INDEX timestamp_idx ON pre_commit(timestamp
  timestamp_ops);
