-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE transaction (
    id SERIAL PRIMARY KEY,
    timestamp timestamp without time zone NOT NULL,
    gas_wanted integer DEFAULT 0,
    gas_used integer DEFAULT 0,
    height integer NOT NULL REFERENCES block(height),
    txhash character varying(64) NOT NULL UNIQUE,
    events jsonb DEFAULT '[]'::jsonb,
    messages jsonb NOT NULL DEFAULT '[]'::jsonb,
    fee jsonb NOT NULL DEFAULT '{}'::jsonb,
    signatures jsonb NOT NULL DEFAULT '[]'::jsonb,
    memo character varying(256)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX transaction_pkey ON transaction(id int4_ops);
CREATE UNIQUE INDEX transaction_txhash_key ON transaction(txhash text_ops);
