-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE validator
(
  id SERIAL PRIMARY KEY,
  address character varying(40) NOT NULL UNIQUE,
  consensus_pubkey character varying(83) NOT NULL UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX validator_pkey ON validator(id
int4_ops);
CREATE UNIQUE INDEX validator_address_key ON validator(address
text_ops);
CREATE UNIQUE INDEX validator_consensus_pubkey_key ON validator(consensus_pubkey
text_ops);
