-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE validator
(
    consensus_address TEXT NOT NULL PRIMARY KEY, /* Validator consensus address */
    consensus_pubkey  TEXT NOT NULL UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX validator_pkey ON validator (id int4_ops);
CREATE UNIQUE INDEX validator_address_key ON validator (consensus_address TEXT_PATTERN_OPS);
CREATE UNIQUE INDEX validator_consensus_pubkey_key ON validator (consensus_pubkey TEXT_PATTERN_OPS);
